// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0p8AHMAcruAR7GplKkW2d-5--5I-VWfg',
    appId: '1:389270766939:web:f65d1bfc9903ecababc67e',
    messagingSenderId: '389270766939',
    projectId: 'prueba-flutter-ricardo',
    authDomain: 'prueba-flutter-ricardo.firebaseapp.com',
    storageBucket: 'prueba-flutter-ricardo.firebasestorage.app',
    measurementId: 'G-1PRCBJP6H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANubfAWiVMjKWyaLRhYR289l2LNLRqZQA',
    appId: '1:389270766939:android:e71fca76813541e5abc67e',
    messagingSenderId: '389270766939',
    projectId: 'prueba-flutter-ricardo',
    storageBucket: 'prueba-flutter-ricardo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3yD8Nnuwvscv-r9nY3VstMdkdf5MVfsA',
    appId: '1:389270766939:ios:ce45aebb6ef1d097abc67e',
    messagingSenderId: '389270766939',
    projectId: 'prueba-flutter-ricardo',
    storageBucket: 'prueba-flutter-ricardo.firebasestorage.app',
    iosBundleId: 'com.example.pruebaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3yD8Nnuwvscv-r9nY3VstMdkdf5MVfsA',
    appId: '1:389270766939:ios:ce45aebb6ef1d097abc67e',
    messagingSenderId: '389270766939',
    projectId: 'prueba-flutter-ricardo',
    storageBucket: 'prueba-flutter-ricardo.firebasestorage.app',
    iosBundleId: 'com.example.pruebaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0p8AHMAcruAR7GplKkW2d-5--5I-VWfg',
    appId: '1:389270766939:web:ff49e840fec87382abc67e',
    messagingSenderId: '389270766939',
    projectId: 'prueba-flutter-ricardo',
    authDomain: 'prueba-flutter-ricardo.firebaseapp.com',
    storageBucket: 'prueba-flutter-ricardo.firebasestorage.app',
    measurementId: 'G-MKD70VKNDZ',
  );
}
